version: '3'
services:
  postgres_source:
    image: postgres:13
    container_name: banco_origem
    environment:
      POSTGRES_USER: ${POSTGRES_USER:?set in .env}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?set in .env}
      POSTGRES_DB: ${POSTGRES_DB:?set in .env}
    ports:
      - "5433:5432" # MUDANÃ‡A AQUI: Porta externa 5433
